  // ═══════════════════════════════════════════════════════
  // QUESITI-PIANO — Piano di studio della PROVA SCRITTA.
  // Tassonomia DEDICATA allo scritto (più granulare delle materie quiz):
  // materia → argomento (gruppo preciso di articoli) con n_quesiti previsti.
  // La mappa di Prova Scritta si costruisce da qui: mostra la copertura
  // (quesiti caricati / previsti) anche quando i quesiti non sono ancora
  // tutti presenti. I quesiti (quesiti-data.js) si agganciano via
  // materia_id + argomento_id identici a quelli di questo piano.
  //
  // Generato dal prompt "Fase A" (piano unificato R1+R2+TS, 236 quesiti).
  // ═══════════════════════════════════════════════════════

  window.CM_QUESITI_PIANO = {
    "bando": "Piano unificato: RIPAM Difesa 1100 (R1) + RIPAM 3997 (R2) + Comune di Trieste Istruttore C (TS)",
    "note_generali": "Il campo 'bandi' indica a quale procedura si applica: R1=RIPAM Difesa 1100, R2=RIPAM 3997, TS=Trieste.",
    "totale_quesiti_previsti": 327,
    "materie": [
      { "materia_id": "M01_legge_241", "materia": "L. 241/1990 — Procedimento Amministrativo e Accesso", "bandi": ["R1","R2","TS"], "argomenti": [
        { "argomento_id": "A01_principi_rp", "argomento": "Principi generali del procedimento e responsabile del procedimento", "legge": "L. 241/1990 artt. 1-6-bis", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 1, "progressivo_a": 3 },
        { "argomento_id": "A02_partecipazione", "argomento": "Comunicazione di avvio, partecipazione, preavviso di rigetto", "legge": "L. 241/1990 artt. 7-10-bis", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 4, "progressivo_a": 6 },
        { "argomento_id": "A03_conclusione_silenzio", "argomento": "Conclusione del procedimento: obbligo di provvedere, silenzio-inadempimento, termini", "legge": "L. 241/1990 artt. 2-2-bis", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 7, "progressivo_a": 9 },
        { "argomento_id": "A04_semplificazione_scia", "argomento": "Semplificazione: SCIA, silenzio-assenso, autocertificazione nel procedimento", "legge": "L. 241/1990 artt. 19-20; D.Lgs. 126/2016", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 10, "progressivo_a": 12 },
        { "argomento_id": "A05_conferenza_servizi", "argomento": "Conferenza di servizi: modelli, funzionamento, determinazione conclusiva", "legge": "L. 241/1990 artt. 14-14-quinquies", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 13, "progressivo_a": 15 },
        { "argomento_id": "A06_atti_provvedimento", "argomento": "Il provvedimento amministrativo: efficacia, esecutività, esecutorietà", "legge": "L. 241/1990 artt. 21-bis–21-quater", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 16, "progressivo_a": 18 },
        { "argomento_id": "A07_autotutela", "argomento": "Autotutela: annullamento d'ufficio, revoca, convalida, recesso", "legge": "L. 241/1990 artt. 21-quinquies–21-nonies", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 19, "progressivo_a": 21 },
        { "argomento_id": "A08_accesso_documentale", "argomento": "Accesso documentale: legittimazione, procedura, limiti, difensivo", "legge": "L. 241/1990 artt. 22-28; DPR 184/2006", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 22, "progressivo_a": 24 }
      ]},
      { "materia_id": "M02_dlgs_165", "materia": "D.Lgs. 165/2001 — Ordinamento del Lavoro Pubblico", "bandi": ["R1","R2","TS"], "argomenti": [
        { "argomento_id": "A09_principi_organizzazione", "argomento": "Principi generali, fonti del rapporto di lavoro e organizzazione PA", "legge": "D.Lgs. 165/2001 artt. 1-6", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 25, "progressivo_a": 27 },
        { "argomento_id": "A10_dotazioni_fabbisogni", "argomento": "Dotazioni organiche, PIAO, pianificazione dei fabbisogni", "legge": "D.Lgs. 165/2001 artt. 6-6-ter", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 28, "progressivo_a": 30 },
        { "argomento_id": "A11_reclutamento_concorsi", "argomento": "Reclutamento: concorso pubblico, scorrimento graduatorie, mobilità, assunzioni obbligatorie", "legge": "D.Lgs. 165/2001 artt. 35-36; DPR 487/1994", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 31, "progressivo_a": 33 },
        { "argomento_id": "A12_contrattazione_aran", "argomento": "Contrattazione collettiva nazionale e integrativa; ARAN; sistema delle relazioni sindacali", "legge": "D.Lgs. 165/2001 artt. 40-47", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 34, "progressivo_a": 36 },
        { "argomento_id": "A13_incompatibilita_incarichi", "argomento": "Incompatibilità, cumulo di incarichi, conflitto di interessi, regime delle autorizzazioni", "legge": "D.Lgs. 165/2001 art. 53; D.Lgs. 39/2013", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 37, "progressivo_a": 39 },
        { "argomento_id": "A14_disciplinare_illeciti", "argomento": "Illeciti disciplinari, procedimento, sanzioni, destituzione, licenziamento", "legge": "D.Lgs. 165/2001 artt. 55-55-octies", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 40, "progressivo_a": 42 },
        { "argomento_id": "A15_responsabilita_dirigenziale", "argomento": "Responsabilità dirigenziale: valutazione, revoca incarico, decadenza automatica", "legge": "D.Lgs. 165/2001 artt. 17-21", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 43, "progressivo_a": 45 }
      ]},
      { "materia_id": "M03_dpr_62", "materia": "DPR 62/2013 — Codice di Comportamento", "bandi": ["R1","R2","TS"], "argomenti": [
        { "argomento_id": "A16_principi_ambito", "argomento": "Principi generali, ambito di applicazione e obblighi generali", "legge": "DPR 62/2013 artt. 1-3", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 46, "progressivo_a": 48 },
        { "argomento_id": "A17_regali_conflitti", "argomento": "Regali e vantaggi; conflitto di interessi; obblighi di comunicazione e astensione", "legge": "DPR 62/2013 artt. 4-7", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 49, "progressivo_a": 51 },
        { "argomento_id": "A18_comportamento_servizio", "argomento": "Comportamento in servizio, rapporti con il pubblico, utilizzo di beni e risorse pubbliche", "legge": "DPR 62/2013 artt. 8-13", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 52, "progressivo_a": 54 },
        { "argomento_id": "A19_violazioni_sanzioni_codice", "argomento": "Violazioni e sanzioni disciplinari del codice; responsabilità del dirigente; codici di ente", "legge": "DPR 62/2013 artt. 14-17", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 55, "progressivo_a": 57 }
      ]},
      { "materia_id": "M04_anticorruzione", "materia": "L. 190/2012 — Anticorruzione e Whistleblowing", "bandi": ["R1","R2","TS"], "argomenti": [
        { "argomento_id": "A20_anac_pna_rpct", "argomento": "ANAC, PNA, RPCT, PTPCT: ruoli, poteri e contenuti del piano", "legge": "L. 190/2012 art. 1 commi 1-12", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 58, "progressivo_a": 60 },
        { "argomento_id": "A21_misure_preventive", "argomento": "Misure di prevenzione: rotazione, inconferibilità, incompatibilità, formazione obbligatoria", "legge": "L. 190/2012 art. 1 commi 14-57; D.Lgs. 39/2013", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 61, "progressivo_a": 63 },
        { "argomento_id": "A22_whistleblowing", "argomento": "Tutela del segnalante (whistleblowing): canali, protezioni, divieto di ritorsione", "legge": "D.Lgs. 24/2023; L. 190/2012 art. 1 commi 59-65", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 64, "progressivo_a": 66 }
      ]},
      { "materia_id": "M05_trasparenza", "materia": "D.Lgs. 33/2013 — Trasparenza e Accesso Civico", "bandi": ["R1","R2","TS"], "argomenti": [
        { "argomento_id": "A23_principi_trasparenza", "argomento": "Principi generali della trasparenza, obblighi di pubblicazione, vigilanza e sanzioni", "legge": "D.Lgs. 33/2013 artt. 1-7; 43-47", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 67, "progressivo_a": 69 },
        { "argomento_id": "A24_accesso_civico_semplice", "argomento": "Accesso civico semplice: oggetto, procedura, limiti", "legge": "D.Lgs. 33/2013 art. 5 comma 1", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 70, "progressivo_a": 72 },
        { "argomento_id": "A25_foia", "argomento": "Accesso civico generalizzato (FOIA): diritto, limiti, bilanciamento, riesame ANAC", "legge": "D.Lgs. 33/2013 art. 5 comma 2 e art. 5-bis; Linee guida ANAC n. 1309/2016", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 73, "progressivo_a": 75 },
        { "argomento_id": "A26_obblighi_pubblicazione", "argomento": "Obblighi specifici di pubblicazione: organizzazione, personale, atti generali, provvedimenti, contratti", "legge": "D.Lgs. 33/2013 artt. 13-29", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 76, "progressivo_a": 78 }
      ]},
      { "materia_id": "M06_gdpr", "materia": "GDPR Reg. UE 2016/679 + D.Lgs. 196/2003 — Protezione dei Dati Personali", "bandi": ["R1","R2","TS"], "argomenti": [
        { "argomento_id": "A27_principi_basi_giuridiche", "argomento": "Principi del trattamento e basi giuridiche (liceità, consenso, contratto, obbligo legale…)", "legge": "GDPR artt. 5-6", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 79, "progressivo_a": 81 },
        { "argomento_id": "A28_definizioni_categorie", "argomento": "Definizioni fondamentali; categorie particolari di dati e dati giudiziari", "legge": "GDPR artt. 4; 9-10", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 82, "progressivo_a": 84 },
        { "argomento_id": "A29_diritti_interessato_1", "argomento": "Diritti dell'interessato – prima parte: informativa, accesso, rettifica, cancellazione, limitazione", "legge": "GDPR artt. 12-18", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 85, "progressivo_a": 87 },
        { "argomento_id": "A30_diritti_interessato_2", "argomento": "Diritti dell'interessato – seconda parte: portabilità, opposizione, profilazione automatizzata", "legge": "GDPR artt. 19-22", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 88, "progressivo_a": 90 },
        { "argomento_id": "A31_titolare_responsabile", "argomento": "Titolare, responsabile del trattamento, sub-responsabile, persone autorizzate; accordi ex art. 28", "legge": "GDPR artt. 24-29", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 91, "progressivo_a": 93 },
        { "argomento_id": "A32_sicurezza_databreach_dpia", "argomento": "Misure di sicurezza; data breach (notifica Garante e all'interessato); DPIA", "legge": "GDPR artt. 32-35", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 94, "progressivo_a": 96 },
        { "argomento_id": "A33_dpo_garante_sanzioni", "argomento": "DPO: nomina, funzioni, indipendenza; Garante: poteri correttivi e autorizzativi; sanzioni GDPR", "legge": "GDPR artt. 37-39; 51-58; 83-84; D.Lgs. 196/2003 artt. 2-ter–2-octies", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 97, "progressivo_a": 99 }
      ]},
      { "materia_id": "M07_diritto_penale_pa", "materia": "Diritto Penale — Reati contro la PA e Responsabilità del Dipendente Pubblico", "bandi": ["R1","R2","TS"], "argomenti": [
        { "argomento_id": "A34_qualifiche_soggettive", "argomento": "Qualifiche soggettive penali: pubblico ufficiale, incaricato di pubblico servizio, esercente di pubblica necessità", "legge": "Cod. pen. artt. 357-360", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 100, "progressivo_a": 102 },
        { "argomento_id": "A35_reati_propri_pu", "argomento": "Reati propri del PU: peculato (314), concussione (317), corruzione propria e impropria (318-319-ter), induzione indebita (319-quater)", "legge": "Cod. pen. artt. 314-319-quater", "bandi": ["R1","R2","TS"], "n_quesiti": 4, "progressivo_da": 103, "progressivo_a": 106 },
        { "argomento_id": "A36_altri_reati_pa", "argomento": "Abuso d'ufficio, rivelazione di segreti, istigazione alla corruzione, traffico di influenze illecite", "legge": "Cod. pen. artt. 323-326; 322; 346-bis", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 107, "progressivo_a": 109 },
        { "argomento_id": "A37_responsabilita_quadro", "argomento": "Quadro generale delle responsabilità del dipendente pubblico: penale, disciplinare, civile, contabile (Corte dei conti)", "legge": "L. 20/1994; Cod. pen. artt. 314 ss.; D.Lgs. 165/2001 artt. 55 ss.", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 110, "progressivo_a": 112 }
      ]},
      { "materia_id": "M08_diritto_costituzionale", "materia": "Diritto Costituzionale", "bandi": ["TS"], "argomenti": [
        { "argomento_id": "A38_principi_diritti_civili", "argomento": "Principi fondamentali e diritti civili nella Costituzione (artt. 1-28, selezione PA-rilevante)", "legge": "Cost. artt. 1-28", "bandi": ["TS"], "n_quesiti": 3, "progressivo_da": 113, "progressivo_a": 115 },
        { "argomento_id": "A39_fonti_diritto", "argomento": "Fonti del diritto: gerarchia, riserva di legge, decreto-legge, decreto legislativo, regolamenti", "legge": "Cost. artt. 70-77; Disp. prel. Cod. civ. artt. 1-9", "bandi": ["TS"], "n_quesiti": 3, "progressivo_da": 116, "progressivo_a": 118 },
        { "argomento_id": "A40_parlamento_governo", "argomento": "Parlamento e procedimento legislativo; Governo, Presidente del Consiglio", "legge": "Cost. artt. 55-82; 92-98", "bandi": ["TS"], "n_quesiti": 3, "progressivo_da": 119, "progressivo_a": 121 },
        { "argomento_id": "A41_pa_costituzione", "argomento": "La PA nella Costituzione: artt. 97-98, principio di imparzialità e buon andamento", "legge": "Cost. artt. 97-98", "bandi": ["TS"], "n_quesiti": 3, "progressivo_da": 122, "progressivo_a": 124 },
        { "argomento_id": "A42_autonomie_corte_cost", "argomento": "Autonomie locali nella Costituzione (artt. 114-119); Corte Costituzionale (artt. 134-137)", "legge": "Cost. artt. 114-120; 134-137", "bandi": ["TS"], "n_quesiti": 3, "progressivo_da": 125, "progressivo_a": 127 }
      ]},
      { "materia_id": "M09_diritto_civile", "materia": "Diritto Civile (Libri III, IV, VI)", "bandi": ["TS"], "argomenti": [
        { "argomento_id": "A43_obbligazioni", "argomento": "Obbligazioni: fonti, adempimento, inadempimento, mora, estinzione", "legge": "Cod. civ. artt. 1173-1320", "bandi": ["TS"], "n_quesiti": 3, "progressivo_da": 128, "progressivo_a": 130 },
        { "argomento_id": "A44_contratto_generale", "argomento": "Contratto in generale: formazione, requisiti, validità, nullità, annullabilità", "legge": "Cod. civ. artt. 1321-1418", "bandi": ["TS"], "n_quesiti": 3, "progressivo_da": 131, "progressivo_a": 133 },
        { "argomento_id": "A45_contratto_effetti", "argomento": "Effetti, interpretazione, risoluzione e rescissione del contratto", "legge": "Cod. civ. artt. 1419-1469", "bandi": ["TS"], "n_quesiti": 3, "progressivo_da": 134, "progressivo_a": 136 },
        { "argomento_id": "A46_responsabilita_civile", "argomento": "Responsabilità extracontrattuale: danno ingiusto, nesso causale, responsabilità oggettiva", "legge": "Cod. civ. artt. 2043-2059", "bandi": ["TS"], "n_quesiti": 3, "progressivo_da": 137, "progressivo_a": 139 },
        { "argomento_id": "A47_proprieta_possesso", "argomento": "Proprietà (Libro III): contenuto, limiti, modi di acquisto; possesso e azioni possessorie", "legge": "Cod. civ. artt. 810-1172", "bandi": ["TS"], "n_quesiti": 3, "progressivo_da": 140, "progressivo_a": 142 },
        { "argomento_id": "A48_tutela_diritti_prescrizione", "argomento": "Tutela dei diritti (Libro VI): prove, esecuzione forzata, prescrizione e decadenza", "legge": "Cod. civ. artt. 2697-2969", "bandi": ["TS"], "n_quesiti": 3, "progressivo_da": 143, "progressivo_a": 145 }
      ]},
      { "materia_id": "M10_tuel", "materia": "D.Lgs. 267/2000 — TUEL (Ordinamento Enti Locali)", "bandi": ["TS"], "argomenti": [
        { "argomento_id": "A49_tuel_principi_autonomia", "argomento": "Principi generali e autonomia locale; enti locali e loro funzioni", "legge": "D.Lgs. 267/2000 artt. 1-8", "bandi": ["TS"], "n_quesiti": 3, "progressivo_da": 146, "progressivo_a": 148 },
        { "argomento_id": "A50_consiglio_comunale", "argomento": "Consiglio comunale: composizione, competenze esclusive, funzionamento", "legge": "D.Lgs. 267/2000 artt. 36-42", "bandi": ["TS"], "n_quesiti": 3, "progressivo_da": 149, "progressivo_a": 151 },
        { "argomento_id": "A51_sindaco_giunta", "argomento": "Sindaco e Giunta: nomina, competenze, rapporto fiduciario, mozione di sfiducia", "legge": "D.Lgs. 267/2000 artt. 46-51", "bandi": ["TS"], "n_quesiti": 3, "progressivo_da": 152, "progressivo_a": 154 },
        { "argomento_id": "A52_dirigenti_responsabili", "argomento": "Competenze dirigenti e responsabili dei servizi; pareri obbligatori e responsabilità", "legge": "D.Lgs. 267/2000 artt. 49; 107-111", "bandi": ["TS"], "n_quesiti": 3, "progressivo_da": 155, "progressivo_a": 157 },
        { "argomento_id": "A53_forme_associative", "argomento": "Forme associative: convenzioni, consorzi, unioni di comuni, accordi di programma", "legge": "D.Lgs. 267/2000 artt. 30-34", "bandi": ["TS"], "n_quesiti": 3, "progressivo_da": 158, "progressivo_a": 160 },
        { "argomento_id": "A54_principi_bilancio_tuel", "argomento": "Principi finanziari e struttura del bilancio dell'ente locale", "legge": "D.Lgs. 267/2000 artt. 149-164", "bandi": ["TS"], "n_quesiti": 3, "progressivo_da": 161, "progressivo_a": 163 },
        { "argomento_id": "A55_gestione_entrate_spese", "argomento": "Gestione delle entrate e delle spese: fasi dell'impegno, liquidazione, ordinazione, pagamento", "legge": "D.Lgs. 267/2000 artt. 178-186", "bandi": ["TS"], "n_quesiti": 3, "progressivo_da": 164, "progressivo_a": 166 },
        { "argomento_id": "A56_equilibri_debiti_dissesto", "argomento": "Salvaguardia degli equilibri, debiti fuori bilancio, dissesto finanziario e riequilibrio pluriennale", "legge": "D.Lgs. 267/2000 artt. 193-194; 242-269", "bandi": ["TS"], "n_quesiti": 3, "progressivo_da": 167, "progressivo_a": 169 },
        { "argomento_id": "A57_revisione_economica", "argomento": "Organo di revisione economico-finanziaria: composizione, funzioni, pareri, relazione", "legge": "D.Lgs. 267/2000 artt. 234-241", "bandi": ["TS"], "n_quesiti": 3, "progressivo_da": 170, "progressivo_a": 172 }
      ]},
      { "materia_id": "M11_dlgs_118", "materia": "D.Lgs. 118/2011 — Contabilità Armonizzata", "bandi": ["TS"], "argomenti": [
        { "argomento_id": "A58_principi_contabili_armonia", "argomento": "Principi contabili generali e competenza finanziaria potenziata", "legge": "D.Lgs. 118/2011 artt. 1-3 + All. 1", "bandi": ["TS"], "n_quesiti": 3, "progressivo_da": 173, "progressivo_a": 175 },
        { "argomento_id": "A59_struttura_bilancio_armonizzato", "argomento": "Struttura del bilancio armonizzato: missioni, programmi, titoli, tipologie, categorie", "legge": "D.Lgs. 118/2011 artt. 11-17 + All. 13-14", "bandi": ["TS"], "n_quesiti": 3, "progressivo_da": 176, "progressivo_a": 178 },
        { "argomento_id": "A60_documenti_programmazione", "argomento": "DUP, bilancio di previsione, PEG, rendiconto; fondo pluriennale vincolato (FPV) e FCDE", "legge": "D.Lgs. 118/2011 artt. 151-155; All. 4/1", "bandi": ["TS"], "n_quesiti": 3, "progressivo_da": 179, "progressivo_a": 181 }
      ]},
      { "materia_id": "M12_performance", "materia": "D.Lgs. 150/2009 — Performance e PIAO", "bandi": ["R1","R2","TS"], "argomenti": [
        { "argomento_id": "A61_ciclo_performance", "argomento": "Ciclo della performance: piano, relazione, OIV, trasparenza; integrazione con PIAO", "legge": "D.Lgs. 150/2009 (testo aggiornato D.Lgs. 74/2017); DPR 81/2022 (PIAO)", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 182, "progressivo_a": 184 }
      ]},
      { "materia_id": "M13_contratti_pubblici", "materia": "D.Lgs. 36/2023 — Codice dei Contratti Pubblici", "bandi": ["R1","R2","TS"], "argomenti": [
        { "argomento_id": "A62_principi_contratti", "argomento": "Principi generali del nuovo codice: fiducia, risultato, accesso al mercato, legalità", "legge": "D.Lgs. 36/2023 artt. 1-12", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 185, "progressivo_a": 187 },
        { "argomento_id": "A63_procedure_affidamento", "argomento": "Soglie europee, procedure di affidamento (aperta, ristretta, negoziata, affidamento diretto), RUP, criteri di aggiudicazione", "legge": "D.Lgs. 36/2023 artt. 14-17; 50-58; 73-76", "bandi": ["R1","R2","TS"], "n_quesiti": 4, "progressivo_da": 188, "progressivo_a": 191 },
        { "argomento_id": "A64_consip_mepa", "argomento": "Acquisti centralizzati: CONSIP, soggetti aggregatori, mercato elettronico (MEPA), accordi quadro", "legge": "D.Lgs. 36/2023 artt. 61-65; L. 488/1999 art. 26", "bandi": ["TS"], "n_quesiti": 3, "progressivo_da": 192, "progressivo_a": 194 }
      ]},
      { "materia_id": "M14_dpr_445", "materia": "DPR 445/2000 — Documentazione Amministrativa", "bandi": ["R1","R2","TS"], "argomenti": [
        { "argomento_id": "A65_dsc_dsan", "argomento": "Dichiarazioni sostitutive di certificazione (DSC) e di atto notorio (DSAN); autenticazione di firma e copie", "legge": "DPR 445/2000 artt. 19-25; 46-47", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 195, "progressivo_a": 197 },
        { "argomento_id": "A66_once_only_controlli", "argomento": "Principio once only; controlli sulle dichiarazioni; sanzioni per false dichiarazioni; procedure concorsuali", "legge": "DPR 445/2000 artt. 38-43; 71-76", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 198, "progressivo_a": 200 }
      ]},
      { "materia_id": "M15_cad", "materia": "D.Lgs. 82/2005 — Codice dell'Amministrazione Digitale (CAD)", "bandi": ["R1","R2","TS"], "argomenti": [
        { "argomento_id": "A67_cad_principi_diritti", "argomento": "Definizioni, principi generali e diritti di cittadinanza digitale", "legge": "D.Lgs. 82/2005 artt. 1-9", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 201, "progressivo_a": 203 },
        { "argomento_id": "A68_documento_informatico_firme", "argomento": "Documento informatico e firme elettroniche (semplice, avanzata, qualificata, digitale); validità giuridica", "legge": "D.Lgs. 82/2005 artt. 20-25; Reg. UE eIDAS 910/2014", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 204, "progressivo_a": 206 },
        { "argomento_id": "A69_conservazione_formazione", "argomento": "Formazione, gestione e conservazione dei documenti informatici; protocollo informatico", "legge": "D.Lgs. 82/2005 artt. 40-44; DPR 445/2000; Linee guida AgID sulla formazione documentale", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 207, "progressivo_a": 209 },
        { "argomento_id": "A70_pec_spid_domicilio", "argomento": "PEC e domicilio digitale; SPID e CIE (identità digitale); trasmissione telematica tra PA e verso privati", "legge": "D.Lgs. 82/2005 artt. 45-49; 64-64-bis", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 210, "progressivo_a": 212 },
        { "argomento_id": "A71_interoperabilita_open_data", "argomento": "Interoperabilità, open data, riuso del software PA, accessibilità dei servizi digitali", "legge": "D.Lgs. 82/2005 artt. 50-68; Linee guida AgID", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 213, "progressivo_a": 215 },
        { "argomento_id": "A72_cybersecurity", "argomento": "Cybersicurezza per la PA: minacce, buone pratiche, ACN, L. 90/2024, gestione degli incidenti", "legge": "L. 90/2024; D.Lgs. 82/2005; Vademecum ACN; Direttiva NIS2 (D.Lgs. 138/2024)", "bandi": ["R1","R2","TS"], "n_quesiti": 3, "progressivo_da": 216, "progressivo_a": 218 }
      ]},
      { "materia_id": "M16_diritto_ue", "materia": "Elementi di Diritto dell'Unione Europea", "bandi": ["R1","R2"], "argomenti": [
        { "argomento_id": "A73_istituzioni_fonti_ue", "argomento": "Istituzioni UE: Parlamento, Consiglio, Commissione, Corte di giustizia; fonti del diritto UE (regolamenti, direttive, decisioni)", "legge": "TUE artt. 13-19; TFUE artt. 288-299", "bandi": ["R1","R2"], "n_quesiti": 3, "progressivo_da": 219, "progressivo_a": 221 },
        { "argomento_id": "A74_principi_ue_mercato", "argomento": "Principi fondamentali UE: sussidiarietà, proporzionalità, primato; libertà fondamentali del mercato interno", "legge": "TUE artt. 3-6; TFUE artt. 26-66", "bandi": ["R1","R2"], "n_quesiti": 3, "progressivo_da": 222, "progressivo_a": 224 },
        { "argomento_id": "A75_diritti_fondamentali_ue", "argomento": "Carta dei diritti fondamentali UE; cittadinanza europea; procedure di infrazione", "legge": "Carta dei diritti fondamentali UE; TFUE artt. 258-260", "bandi": ["R1","R2"], "n_quesiti": 3, "progressivo_da": 225, "progressivo_a": 227 }
      ]},
      { "materia_id": "M17_ordinamento_difesa", "materia": "Ordinamento del Ministero della Difesa", "bandi": ["R1"], "argomenti": [
        { "argomento_id": "A76_struttura_difesa", "argomento": "Organizzazione del Ministero della Difesa: struttura centrale (Segretariato, SMD, Comandi di vertice), aree e forze armate", "legge": "D.Lgs. 66/2010 (COM) artt. 1-40; L. 25/1997", "bandi": ["R1"], "n_quesiti": 3, "progressivo_da": 228, "progressivo_a": 230 },
        { "argomento_id": "A77_personale_civile_difesa", "argomento": "Personale civile della Difesa: categorie, stato giuridico, reclutamento, progressioni di carriera, CCNL comparto Difesa", "legge": "D.Lgs. 66/2010 Libro IV; D.Lgs. 165/2001; CCNL Difesa", "bandi": ["R1"], "n_quesiti": 3, "progressivo_da": 231, "progressivo_a": 233 }
      ]},
      { "materia_id": "M18_inglese", "materia": "Lingua Inglese (livello A2 QCER)", "bandi": ["R1","R2"], "argomenti": [
        { "argomento_id": "A78_inglese_a2", "argomento": "Vocabolario, strutture grammaticali di base e comprensione di testi brevi in contesto lavorativo-amministrativo (livello A2)", "legge": "Quadro Comune Europeo di Riferimento per le lingue (QCER) — descrittori A2", "bandi": ["R1","R2"], "n_quesiti": 3, "progressivo_da": 234, "progressivo_a": 236 }
      ]},
      { "materia_id": "M19_competenze_trasversali", "materia": "Competenze Comportamentali e Organizzative (art. 35-quater D.Lgs. 165/2001)", "bandi": ["MM"], "argomenti": [
        { "argomento_id": "A79_problem_solving_pa", "argomento": "Problem solving nella PA: analisi del problema, identificazione delle soluzioni, gestione delle priorità e decision making", "legge": "Art. 35-quater D.Lgs. 165/2001; Linee guida DFP sulla selezione per competenze", "bandi": ["MM"], "n_quesiti": 3, "progressivo_da": 237, "progressivo_a": 239 },
        { "argomento_id": "A80_lavoro_gruppo_comunicazione", "argomento": "Lavoro di gruppo, comunicazione organizzativa interna e gestione delle relazioni con l'utenza", "legge": "Art. 35-quater D.Lgs. 165/2001; DPR 62/2013 artt. 8-13; D.Lgs. 150/2009 art. 9", "bandi": ["MM"], "n_quesiti": 3, "progressivo_da": 240, "progressivo_a": 242 },
        { "argomento_id": "A81_adattamento_stress_resilienza", "argomento": "Adattamento organizzativo, gestione dello stress lavorativo, resilienza e flessibilità nel contesto della PA", "legge": "Art. 35-quater D.Lgs. 165/2001; D.Lgs. 81/2008 artt. 28-32 (stress lavoro-correlato); DPR 62/2013 art. 11", "bandi": ["MM"], "n_quesiti": 3, "progressivo_da": 243, "progressivo_a": 245 },
        { "argomento_id": "A82_etica_orientamento_risultato", "argomento": "Orientamento al risultato, etica del servizio pubblico, responsabilità e accountability del dipendente comunale", "legge": "DPR 62/2013 artt. 1-3; D.Lgs. 150/2009 artt. 3-5; Cost. artt. 54; 97-98", "bandi": ["MM"], "n_quesiti": 3, "progressivo_da": 246, "progressivo_a": 248 }
      ]},
      { "materia_id": "M20_informatica_applicata", "materia": "Informatica Applicata per Enti Locali — Strumenti Operativi", "bandi": ["MM"], "argomenti": [
        { "argomento_id": "A83_office_gestione_documenti", "argomento": "Pacchetto Office nella PA: Word (redazione atti e lettere), Excel (fogli di calcolo e tabelle), uso pratico nel contesto amministrativo", "legge": "D.Lgs. 82/2005 artt. 40-44; Linee guida AgID formazione documentale", "bandi": ["MM"], "n_quesiti": 3, "progressivo_da": 249, "progressivo_a": 251 },
        { "argomento_id": "A84_sistemi_gestionali_comunali", "argomento": "Sistemi gestionali degli enti locali: protocollo informatico, delibere e determine elettroniche, sistemi di contabilità e gestione del personale", "legge": "D.Lgs. 82/2005 artt. 40-44; DPR 445/2000 artt. 53-68; D.Lgs. 267/2000 art. 169", "bandi": ["MM"], "n_quesiti": 3, "progressivo_da": 252, "progressivo_a": 254 },
        { "argomento_id": "A85_comunicazione_digitale_istituzionale", "argomento": "Comunicazione digitale istituzionale: sito web comunale, social media della PA, newsletter, gestione della posta elettronica istituzionale e PEC", "legge": "D.Lgs. 82/2005 artt. 45-49; D.Lgs. 33/2013 artt. 1-7; D.Lgs. 106/2018 (accessibilità web)", "bandi": ["MM"], "n_quesiti": 3, "progressivo_da": 255, "progressivo_a": 257 },
        { "argomento_id": "A86_sicurezza_informatica_base", "argomento": "Sicurezza informatica di base per il dipendente comunale: password, phishing, uso corretto dei dispositivi e delle reti, BYOD e misure minime ACN", "legge": "L. 90/2024; Misure minime ICT per PA (Circolare AgID n. 2/2017); D.Lgs. 82/2005 art. 51", "bandi": ["MM"], "n_quesiti": 3, "progressivo_da": 258, "progressivo_a": 260 }
      ]},
      { "materia_id": "M21_tributi_locali", "materia": "Tributi Locali — IMU, TARI, Imposta di Soggiorno", "bandi": ["tracce_reali"], "argomenti": [
        { "argomento_id": "A87_imu_base_imponibile", "argomento": "IMU: normativa di riferimento, presupposto, soggetti passivi e base imponibile (D.Lgs. 504/1992; L. 160/2019)", "legge": "L. 160/2019 artt. 1 co. 739-783; D.Lgs. 23/2011", "bandi": ["tracce_reali"], "n_quesiti": 4, "progressivo_da": 261, "progressivo_a": 264 },
        { "argomento_id": "A88_imu_aliquote_riduzioni", "argomento": "IMU: abitazione principale, aliquote, riduzioni di base imponibile, immobili locati a canone concordato, calcolo pratico", "legge": "L. 160/2019 artt. 1 co. 745-760; D.M. 3.11.2021", "bandi": ["tracce_reali"], "n_quesiti": 4, "progressivo_da": 265, "progressivo_a": 268 },
        { "argomento_id": "A89_tari_presupposto", "argomento": "TARI: normativa di riferimento, presupposto impositivo, suscettibilità a produrre rifiuti, riduzioni, utenze domestiche e non domestiche", "legge": "L. 147/2013 artt. 1 co. 641-705; Reg. DPR 158/1999", "bandi": ["tracce_reali"], "n_quesiti": 3, "progressivo_da": 269, "progressivo_a": 271 },
        { "argomento_id": "A90_accertamento_tributi", "argomento": "Accertamento con adesione, autotutela tributaria, ravvedimento operoso nei tributi locali", "legge": "D.Lgs. 218/1997; L. 296/2006; D.Lgs. 471/1997", "bandi": ["tracce_reali"], "n_quesiti": 3, "progressivo_da": 272, "progressivo_a": 274 },
        { "argomento_id": "A91_imposta_soggiorno", "argomento": "Imposta di soggiorno: normativa, presupposto, soggetti obbligati, obblighi del gestore della struttura ricettiva", "legge": "D.Lgs. 23/2011 art. 4; L. 178/2020 art. 1 co. 590-591", "bandi": ["tracce_reali"], "n_quesiti": 3, "progressivo_da": 275, "progressivo_a": 277 }
      ]},
      { "materia_id": "M22_servizi_demografici", "materia": "Servizi Demografici — Anagrafe, Stato Civile, Elettorale", "bandi": ["tracce_reali"], "argomenti": [
        { "argomento_id": "A92_anagrafe_iscrizioni", "argomento": "Anagrafe della popolazione residente: iscrizioni, cancellazioni, AIRE, residenza in tempo reale (D.P.R. 223/1989; L. 1228/1954)", "legge": "D.P.R. 223/1989; L. 1228/1954; D.L. 5/2012 art. 5", "bandi": ["tracce_reali"], "n_quesiti": 3, "progressivo_da": 278, "progressivo_a": 280 },
        { "argomento_id": "A93_stato_civile", "argomento": "Stato civile: ufficiale di stato civile, registri, atti di nascita, matrimonio, morte, unioni civili, separazioni (DPR 396/2000)", "legge": "DPR 396/2000; L. 76/2016 (unioni civili); D.L. 132/2014", "bandi": ["tracce_reali"], "n_quesiti": 3, "progressivo_da": 281, "progressivo_a": 283 },
        { "argomento_id": "A94_liste_elettorali", "argomento": "Liste elettorali: revisione semestrale e dinamica, albo presidenti di seggio e scrutatori, ineleggibilità e incompatibilità (DPR 223/1967)", "legge": "DPR 223/1967; D.Lgs. 267/2000 artt. 60-63", "bandi": ["tracce_reali"], "n_quesiti": 3, "progressivo_da": 284, "progressivo_a": 286 }
      ]},
      { "materia_id": "M23_redazione_atti", "materia": "Redazione Pratica di Atti Amministrativi — Determinazioni, Delibere, Ordinanze", "bandi": ["tracce_reali"], "argomenti": [
        { "argomento_id": "A95_determinazione_spesa", "argomento": "Redazione di determinazione dirigenziale: struttura, contenuto obbligatorio, impegno di spesa, liquidazione, affidamento sotto soglia", "legge": "D.Lgs. 267/2000 artt. 107; 183-186; D.Lgs. 36/2023 artt. 50-55", "bandi": ["tracce_reali"], "n_quesiti": 4, "progressivo_da": 287, "progressivo_a": 290 },
        { "argomento_id": "A96_delibera_giunta_consiglio", "argomento": "Redazione di proposta di deliberazione (Giunta e Consiglio): struttura, pareri obbligatori, pubblicazione, esecutività", "legge": "D.Lgs. 267/2000 artt. 42; 48; 49; 124", "bandi": ["tracce_reali"], "n_quesiti": 3, "progressivo_da": 291, "progressivo_a": 293 },
        { "argomento_id": "A97_ordinanza_sindacale", "argomento": "Redazione di ordinanza sindacale: ordinaria e contingibile e urgente, presupposti, struttura, efficacia (art. 54 TUEL)", "legge": "D.Lgs. 267/2000 artt. 50; 54", "bandi": ["tracce_reali"], "n_quesiti": 3, "progressivo_da": 294, "progressivo_a": 296 }
      ]},
      { "materia_id": "M24_contabilita_tributaria_avanzata", "materia": "Contabilità Tributaria Avanzata — Accertamento, Rimborsi, Split Payment, Reverse Charge", "bandi": ["tracce_reali_2"], "argomenti": [
        { "argomento_id": "A98_avviso_accertamento_imu", "argomento": "Avviso di accertamento IMU: struttura, elementi obbligatori, calcolo dell'imposta omessa, sanzioni e interessi (D.Lgs. 471/1997; L. 296/2006)", "legge": "L. 160/2019; D.Lgs. 471/1997; L. 296/2006 art. 1 co. 161-170", "bandi": ["tracce_reali_2"], "n_quesiti": 3, "progressivo_da": 297, "progressivo_a": 299 },
        { "argomento_id": "A99_rimborso_tributi", "argomento": "Rimborso di tributi comunali indebitamente versati: presupposti, procedimento, determinazione dirigenziale di rimborso IMU (L. 296/2006 art. 1 co. 164)", "legge": "L. 296/2006 art. 1 co. 164; L. 212/2000 art. 2-quater; D.Lgs. 267/2000 artt. 107; 183", "bandi": ["tracce_reali_2"], "n_quesiti": 3, "progressivo_da": 300, "progressivo_a": 302 },
        { "argomento_id": "A100_split_reverse_charge", "argomento": "Split payment e reverse charge nella PA: definizione, ambito applicativo, contabilizzazione finanziaria (D.M. 23.1.2015; art. 17 DPR 633/1972)", "legge": "D.M. 23.1.2015 (split payment); art. 17 co. 5-6 DPR 633/1972 (reverse charge); D.Lgs. 118/2011", "bandi": ["tracce_reali_2"], "n_quesiti": 3, "progressivo_da": 303, "progressivo_a": 305 }
      ]},
      { "materia_id": "M25_gestione_personale", "materia": "Gestione del Personale degli Enti Locali — Retribuzioni, Contratto di Lavoro, Lavoro Flessibile", "bandi": ["tracce_reali_2"], "argomenti": [
        { "argomento_id": "A101_salario_accessorio", "argomento": "Salario accessorio del personale non dirigenziale degli enti locali: componenti, limiti, fondo risorse decentrate (art. 23 D.Lgs. 75/2017; CCNL Funzioni Locali)", "legge": "D.Lgs. 165/2001; D.Lgs. 75/2017 art. 23; CCNL Funzioni Locali 16.11.2022", "bandi": ["tracce_reali_2"], "n_quesiti": 3, "progressivo_da": 306, "progressivo_a": 308 },
        { "argomento_id": "A102_lavoro_flessibile_conguaglio", "argomento": "Lavoro flessibile negli enti locali (contratti a termine, somministrazione, lavoro accessorio) e operazioni di fine anno: conguaglio fiscale e previdenziale", "legge": "D.Lgs. 81/2015; D.Lgs. 165/2001 artt. 36-38; DPR 917/1986 (TUIR) artt. 23-29", "bandi": ["tracce_reali_2"], "n_quesiti": 3, "progressivo_da": 309, "progressivo_a": 311 },
        { "argomento_id": "A103_contratto_individuale_lavoro", "argomento": "Il contratto individuale di lavoro nella PA: forma, contenuto obbligatorio, periodo di prova, obbligo di permanenza (D.Lgs. 165/2001 artt. 35-36; CCNL)", "legge": "D.Lgs. 165/2001 artt. 35-36; CCNL Funzioni Locali 16.11.2022; DPR 487/1994", "bandi": ["tracce_reali_2"], "n_quesiti": 3, "progressivo_da": 312, "progressivo_a": 314 }
      ]},
      { "materia_id": "M26_figure_speciali_bilancio", "materia": "Figure Speciali e Istituti Contabili — Segretario, Responsabile Finanziario, Fondo di Riserva, Esercizio Provvisorio", "bandi": ["tracce_reali_2"], "argomenti": [
        { "argomento_id": "A104_segretario_direttore_generale", "argomento": "Segretario Comunale e Direttore Generale: nomina, funzioni, rapporto con Sindaco e dirigenti (D.Lgs. 267/2000 artt. 97-99; 108)", "legge": "D.Lgs. 267/2000 artt. 97-99; 108", "bandi": ["tracce_reali_2"], "n_quesiti": 3, "progressivo_da": 315, "progressivo_a": 317 },
        { "argomento_id": "A105_responsabile_finanziario", "argomento": "Responsabile del Servizio Finanziario (art. 153 TUEL): funzioni, visto di regolarità contabile, parere sulla copertura finanziaria, responsabilità", "legge": "D.Lgs. 267/2000 artt. 153; 49; 183", "bandi": ["tracce_reali_2"], "n_quesiti": 3, "progressivo_da": 318, "progressivo_a": 320 },
        { "argomento_id": "A106_fondo_riserva_esercizio_provvisorio", "argomento": "Fondo di riserva: disciplina, utilizzo, delibera di prelievo (art. 166 TUEL). Esercizio provvisorio e gestione provvisoria: presupposti e limiti (art. 163 TUEL)", "legge": "D.Lgs. 267/2000 artt. 163; 166", "bandi": ["tracce_reali_2"], "n_quesiti": 4, "progressivo_da": 321, "progressivo_a": 324 }
      ]},
      { "materia_id": "M27_urp_comunicazione", "materia": "URP, Comunicazione Istituzionale e Accesso ai Documenti — L. 150/2000", "bandi": ["tracce_reali_2"], "argomenti": [
        { "argomento_id": "A107_urp_l150", "argomento": "Ufficio Relazioni con il Pubblico (URP): istituzione, funzioni, comunicazione interna ed esterna della PA (L. 150/2000; D.Lgs. 165/2001 art. 8)", "legge": "L. 150/2000; D.Lgs. 165/2001 art. 8; D.Lgs. 82/2005", "bandi": ["tracce_reali_2"], "n_quesiti": 3, "progressivo_da": 325, "progressivo_a": 327 }
      ]}
    ]
  };
